[sinks.aws_elasticsearch]
  type = "elasticsearch"
  inputs = ["log_json"]
  endpoint = "${AWS_SEARCH_ENDPOINT}"
  mode = "bulk"
  bulk.index = "logs-fly-{{fly.app.name}}-%Y-%m-%d"
  compression = "none"